### ISSUE TITLE
Build UI for scanning and manual checkin

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretixdesk#4]
- [x] Scan field
- [x] Result animation
- [x] display sync status
- [x] sync
- [x] perform actual check-in
- [x] search result design
- [x] perform actual search
- [x] allow to check-in search results with touch or enter
- [x] update search results while typing
- [x] modal progress dialog while checking in a search result
- [x] Fill result card with actual details
- [x] make online/offline switch work
- [x] sync status dialog
- [x] display timeout
- [x] focus grabbing
- [x] support attention flag
- [ ] Support USB scanner that does not send enter key?

**Comment by jfwiebe** [comment]
Hi Raphael!

Believe it or not: This morning I thought about building a "pretixdroid desktop" app that reuses the api code of the pretixdroid app. 

But back to topic: A short question about the way people should use this. Here comes my imagination:

There is a PC running this software with an attached barcode reader, configured in "keyboard" mode. A user scans the configuration barcode and the software goes into a "configured" state (similar to pretixdroid). In this state, the user can scan secrets which will be checked in the same way as pretixdroid does. 

How do you imagine this?

With best regards
Jan Felix

**Comment by raphaelm** [comment]
> Believe it or not: This morning I thought about building a "pretixdroid desktop" app that reuses the api code of the pretixdroid app.

🤣 

> But back to topic: A short question about the way people should use this. Here comes my imagination:
> There is a PC running this software with an attached barcode reader, configured in "keyboard" mode. A user scans the configuration barcode and the software goes into a "configured" state (similar to pretixdroid). In this state, the user can scan secrets which will be checked in the same way as pretixdroid does.

Partially yes. Running this with a USB-keyboard barcode reader should work approximately as you imagine. But I want this application to be useful even if you don't have an USB barcode scanner (the good ones are quite expensive and for small events you might not need it), so manual input of names or selection from an attendee list should also be possible in this cases. Therefore, configuration via the configuration QR code is not sufficient as the only method here (and I might even not implement it at all), but I'm not yet sure what the better configuration input will look like (entering a code? logging in with pretix credentials? downloading a file from pretix and opening it?).

Thanks for your input!
Raphael

**Comment by jfwiebe** [comment]
In my eyes, having a different authentication method (than pretix backend login) for pretixdroid scanners is a feature. I can generate secrets for my entrance scanners and hand the qr codes out (maybe even on paper) or put them somewhere secret in the cashdesk area, so that the scanning-staff can head to the play store, download the app, scan the code and start scanning (which is really a no-brainer for event orga). Instead logging into pretix, creating a team, inviting people, having the users to register etc. is way more complex.

The question is, if we want the same "abstraction" as in pretixdroid. A direct login would make it quite easy and intuitive to use (enter server url, username, password (2FA?); logged in; select event; start working), but this would grant the user to access all events a user has access to, a pretixdroid-style login is per-event only. Is the pretixdesk-user a pretixcontrol-user and is he trusted?

On the other hand, I would like to avoid introducing a fourth (?) way of authentication into pretix. We already have credentials (per-user), API tokens (per-team), pretixdroid-token (per-event).

**Comment by raphaelm** [comment]
I absolutely agree. My current working theory is to drop the pretixdroid tokens as a concept and introduce a new concept called "Devices" instead. Devices are on organizer-level and work roughly like teams (they might even be teams under the hood but displayed differently) and can be instances of pretixdesk, pretixdroid, etc. This removes the requirement of re-configuring the devices for new events, this could just be done via the web interface. I haven't thought this through to the end, I will probably start with supporting pretixdroid tokens in pretixdesk and move to such a device concept later.
